### criar TB_Categoria
 
create table if not exists TB_Categoria (
                id INT generated by default as identity,
                name VARCHAR NOT NULL,
                dt date
            )
 
### criar TB_Funcionario
create table if not exists TB_Funcionario (
                id INT generated by default as identity,
                name VARCHAR NOT NULL,
                dt date
            )
 
### inserir dados TB_Categoria
insert into TB_Categoria (name, dt)
            values('Childrens wear', current_date)
 
### inserir dados TB_Funcionario
insert into TB_Funcionario (name, dt)
            values('Joan Callins', current_date)
